(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.BugPackMarkdown = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  /**
   * Generates GitHub-issue-ready Markdown from bug report data.
   *
   * @param {Object} data
   * @param {string} data.title
   * @param {string} [data.stagingUrl]
   * @param {string} data.browser
   * @param {string} data.os
   * @param {string} [data.testAccountNotes]
   * @param {Array<string>} data.steps
   * @param {string} data.expected
   * @param {string} data.actual
   * @param {Array<Object|File|string>} [data.screenshots]
   * @returns {string} Markdown text
   */
  function generateBugPackMarkdown(data) {
    data = data || {};

    var title = (data.title || '').trim() || 'Untitled Bug Report';
    var stagingUrl = (data.stagingUrl || '').trim();
    var browser = (data.browser || '').trim();
    var os = (data.os || '').trim();
    var testAccountNotes = (data.testAccountNotes || '').trim();
    var expected = (data.expected || '').trim();
    var actual = (data.actual || '').trim();

    // Clean steps: filter out empty steps
    var rawSteps = Array.isArray(data.steps) ? data.steps : [];
    var steps = rawSteps
      .map(function (s) { return typeof s === 'string' ? s.trim() : ''; })
      .filter(function (s) { return s.length > 0; });

    // Screenshots
    var screenshots = Array.isArray(data.screenshots) ? data.screenshots : [];

    var lines = [];

    // Title as H1
    lines.push('# ' + title);
    lines.push('');

    // Environment Section
    lines.push('## Environment');
    lines.push('- **Staging URL:** ' + (stagingUrl ? stagingUrl : '_None provided_'));
    lines.push('- **Browser:** ' + (browser ? browser : '_Not specified_'));
    lines.push('- **Operating System:** ' + (os ? os : '_Not specified_'));
    if (testAccountNotes) {
      lines.push('- **Test Account Notes:** ' + testAccountNotes);
    } else {
      lines.push('- **Test Account Notes:** _None provided_');
    }
    lines.push('');

    // Steps to Reproduce Section
    lines.push('## Steps to Reproduce');
    if (steps.length > 0) {
      steps.forEach(function (step, index) {
        lines.push((index + 1) + '. ' + step);
      });
    } else {
      lines.push('1. _No steps provided_');
    }
    lines.push('');

    // Expected Behavior Section
    lines.push('## Expected Behavior');
    lines.push(expected || '_No expected behavior specified._');
    lines.push('');

    // Actual Behavior Section
    lines.push('## Actual Behavior');
    lines.push(actual || '_No actual behavior specified._');
    lines.push('');

    // Screenshots Section
    lines.push('## Screenshots & Evidence');
    if (screenshots.length > 0) {
      lines.push('### Attached Files');
      screenshots.forEach(function (file, index) {
        var name = (file && typeof file === 'object' && file.name) ? file.name : String(file);
        lines.push('- `' + name + '`');
      });
      lines.push('');
      lines.push('### Placeholders');
      screenshots.forEach(function (file, index) {
        var name = (file && typeof file === 'object' && file.name) ? file.name : String(file);
        lines.push('![screenshot-' + (index + 1) + '](' + name + ')');
      });
    } else {
      lines.push('*No screenshots attached.*');
    }
    lines.push('');

    // Footer note
    lines.push('---');
    lines.push('*Generated by staging-bug-pack*');

    return lines.join('\n');
  }

  /**
   * Helper to format bytes to human readable string
   */
  function formatBytes(bytes) {
    if (typeof bytes !== 'number' || isNaN(bytes) || bytes === 0) return '0 B';
    var k = 1024;
    var sizes = ['B', 'KB', 'MB', 'GB'];
    var i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }

  return {
    generateBugPackMarkdown: generateBugPackMarkdown,
    formatBytes: formatBytes
  };
});
